import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agrilink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white min-h-screen flex flex-col gap-10 justify-center items-center">
          <Image src="/Images/logo-primary.png" alt="Agrilink Primary Logo" width={162} height={101}/>
          <p className="font-fredoka text-[18px]">Better Agriculture In A Digital Way</p>
      </main>
    </>
  );
}
